[project]
name = "smarter"
version = "1.0.0"
description = "Trivia web app using questions from OpenTriviaDatabase"
dependencies = [
    "flask",
]


[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
